### ISSUE TITLE
Wrong type returned for the icon?

### ISSUE THREAD

**Issue by baudren** [spyder-ide/qtawesome#23]
Hi,

thanks for the project, and for using some layer of abstraction to make it simpler to support both PySide and PyQt.

I am getting a strange error on my ubuntu 14.04, though, when trying out the simple example in the readme. I am trying to interface with my [PySide project](https://github.com/baudren/noteorganiser), doing the following:

~~~ python
icon = qta.icon('fa.flag')
button = QtGui.QPushButton(icon, 'New entry', self)  # class instance as parent
~~~

 but when running, I get the following trace:

~~~ python
TypeError: 'PySide.QtGui.QPushButton' called with wrong argument types:
  PySide.QtGui.QPushButton(QIcon, unicode, Editing)
Supported signatures:
  PySide.QtGui.QPushButton(PySide.QtGui.QWidget = None)
  PySide.QtGui.QPushButton(PySide.QtGui.QIcon, unicode, PySide.QtGui.QWidget = None)
  PySide.QtGui.QPushButton(unicode, PySide.QtGui.QWidget = None)
~~~

The `QIcon` is probably coming from `PyQt`? In anyway, it is not understood as `PySide.QtGui.QIcon`.

If that helps to narrow down the problem:
* it seems to be absent on windows 8.1
* I don't have PyQt installed on my system, only PySide

Thanks in advance!

**Comment by SylvainCorlay** [comment]
Thanks for reporting. Does you `Editing` class inherit from `QWidget`?

**Comment by SylvainCorlay** [comment]
@goanpeca this looks like an issue with qtpy.

**Comment by goanpeca** [comment]
Hmmmm I will take a look

**Comment by goanpeca** [comment]
@baudren Can you print the type of `icon`?

```python
print(type(icon))
print(icon.__str__)
print(icon.__unicode__)
print(icon.__repr__)
```

**Comment by goanpeca** [comment]
You do not have PyQt on ubuntu or on windows?

**Comment by goanpeca** [comment]
Can you show the full script/code of the example you are trying to run?

**Comment by baudren** [comment]
Hi @goanpeca 

~~~ python
print(type(icon))
<class 'PyQt4.QtGui.QIcon'>

print(icon.__str__)
<method-wrapper '__str__' of QIcon object at 0x2aab6d9e7d60>

print(icon.__unicode__)
AttributeError: 'QIcon' object has no attribute '__unicode__'

print(icon.__repr__)
<method-wrapper '__repr__' of QIcon object at 0x2b379b695d60>
~~~

@SylvainCorlay , `Editing` inherits from `QtGui.QFrame`, which itself inherits from `QWidget`. And I agree, it might be an issue from `qtpy`.

For the presence of `PyQt` on windows, @egolus is the one for whom it works, maybe he can help with narrowing down the issue.

By the way, I am running `python 2.7.6`, so not the latest.

**Comment by baudren** [comment]
To give a full example (which, by the way, does not work on my other setup, Win8.1, with Anaconda 2.1 (Python 2.7.8), under cygwin):

~~~ python
import sys
from PySide import QtGui
import qtawesome as qta

app = QtGui.QApplication(sys.argv)

wid = QtGui.QWidget()
wid.setWindowTitle('Simple')
icon = qta.icon('fa.flag')
button = QtGui.QPushButton(icon, 'toto', wid)

wid.show()

sys.exit(app.exec_())
~~~

This snippet without the icon displays a `toto` button, but with the icon, gives the same trace as mentionned previously:

~~~ python
Traceback (most recent call last):
  File "simple.py", line 10, in <module>
    button = QtGui.QPushButton(icon, 'Toto', wid)
TypeError: 'PySide.QtGui.QPushButton' called with wrong argument types:
  PySide.QtGui.QPushButton(QIcon, str, PySide.QtGui.QWidget)
Supported signatures:
  PySide.QtGui.QPushButton(PySide.QtGui.QWidget = None)
  PySide.QtGui.QPushButton(PySide.QtGui.QIcon, unicode, PySide.QtGui.QWidget = None)
  PySide.QtGui.QPushButton(unicode, PySide.QtGui.QWidget = None)
~~~

**Comment by goanpeca** [comment]
Can you put this at the top of your script?
```python
import os
print(os.environ['QT_API'])
os.environ['QT_API'] = 'PySide'
```

**Comment by baudren** [comment]
The `print(os.environ['QT_API'])` call results in a `KeyError: 'QT_API'`, which means this was not set (even though the `from PySide` call is done before that).

However, setting `os.environ['QT_API'] = 'PySide'` solves the problem: the icon is displayed (however, now I have the #4 issue, and the icon does not scale with the fontsize.)

What do you recon? Why is the `os.environ` not set properly? Should this be on `qtpy` side?

Thanks

**Comment by goanpeca** [comment]
Not sure if calling PySide is supposed to set an environment variable, I just wanted to check. 

QtPy will autodetect the backend in this order, PyQt5, PyQt4, PySide, unless it is enforced using `os.environ['QT_API'] = 'PySide'`, so if you are using a specific backend in your application you have to ensure that `QT_API` is set accordingly. I will update the readme to make this clear.

**Comment by baudren** [comment]
But precisely - since I do not have PyQt5, nor PyQt4 installed, it should never set it to anything else. I don't think it is right to specify an `os.environ` when there is nothing to be decided for. Shouldn't it fallback to the first available system?

**Comment by goanpeca** [comment]
Well it seems that you do have some remnant of either Qt4 or Qt5 in the system

**Comment by goanpeca** [comment]
In projects that use the shim (qtpy in this case), there will be no problem cause the project and qtawesome will use the same (whatever that is) but if you are using or aiming a specific backend (pyside in this case) this must be set explicitly before calling qtawesome.

**Comment by baudren** [comment]
~~~
pip freeze | grep Qt
   QtAwesome==0.1.10
   QtPy==0.1.2
~~~

I really have nothing from PyQt4 nor 5 on my system.

Indeed, the problem goes away if I replace my `from PySide import QtGui` by a `from qtpy import QtGui`, but this is not a nice solution for existing (potentially large) projects using one or the other. I was expecting a library based on such a thing as `qtpy` to *just work* on a project using either distribution. Otherwise, you are providing a completely *distribution agnostic* package, which is a very good goal in the first place!

**Comment by goanpeca** [comment]
What do you get if you do

```python
import sip
import PyQt4
```

and what do you get when you import

```python
import PyQt5
```

Regarding...
> I was expecting a library based on such a thing as qtpy to just work on a project using either distribution. 

It should and I unfortunately cannot reproduce your error. I am using ubuntu 14.04 and have tested the library with only PyQt4, or with only PySide installed and it works on both cases. 

However if you have PyQt4 and PySide side by side and in your project you only use PySide, then it will not work and hence why I said "I will update the readme to make this clear."

**Comment by baudren** [comment]
Ok, fair enough, the `PyQt4` was not showing on pip but was installed, sorry about the confusion. I don't think that one should have to use a virtual environment to separate `PyQt` from `PySide`, and that `QtPy` should solve the problem, but this is probably a `QtPy` issue.

In any case, now that I realised that I do have `PyQt4`, I went ahead, and tried the exact same code, but doing `from PyQt4 import QtGui`:

~~~ python
import sys
from PyQt4 import QtGui
import qtawesome as qta

app = QtGui.QApplication(sys.argv)

wid = QtGui.QWidget()
wid.setWindowTitle('Simple')
icon = qta.icon('fa.flag')
button = QtGui.QPushButton(icon, 'Toto', wid)

wid.show()

sys.exit(app.exec_())
~~~

 I get this traceback, then:

~~~ python
No handlers could be found for logger "qtpy"
Traceback (most recent call last):
  File "qt.py", line 10, in <module>
    button = QtGui.QPushButton(icon, 'Toto', wid)
TypeError: arguments did not match any overloaded call:
  QPushButton(QWidget parent=None): argument 1 has unexpected type 'PySide.QtGui.QIcon'
  QPushButton(QString, QWidget parent=None): argument 1 has unexpected type 'PySide.QtGui.QIcon'
  QPushButton(QIcon, QString, QWidget parent=None): argument 1 has unexpected type 'PySide.QtGui.QIcon'
~~~

There really seems to be something fishy, here. Why would suddenly the icon get the `PySide` class? It would not be sequential as you are claiming. Maybe this is an indication that the detection of the implementation is faulty, somewhere?

**Comment by goanpeca** [comment]
True, it seems something is weird, but in your specific case is clear that you DO have to define the environment variable.

Can you print the `os.eviron['QT_API']` as I asked before in your example?

**Comment by baudren** [comment]
This time again, `os.environ` does not contain the key `QT_API`. If I use `from qtpy import ...`, then `os.environ['QT_API']` is set to `pyqt`.

**Comment by goanpeca** [comment]
Thanks for reporting but given your actual setup (having both a system PyQt4, and a PySide on pip) you need to set the API to use explicitly, otherwise the automatic detection might result in the error case you found.

**Comment by SylvainCorlay** [comment]
@baudren, another option is for you to use qtpy for your entire project, with the benefit that your software will work with both pyqt and pyside! It is pretty stable (used in Spyder for a while).
At startup, you could print in stdout the one that is used.

**Comment by baudren** [comment]
@SylvainCorlay, sure. I did a quick test by replacing the import statements, and it was breaking the code - I have to adapt all my calls to the PyQt5 syntax, including the tests, which will not be done so quickly. Does `qtpy` support both python 2 and 3, and supports windows/linux well? I can see no build on Travis.

In any case, thank you for the feedback.

**Comment by goanpeca** [comment]
@baudren it does support Python 2 and 3 PyQt5, PyQt4 and PySide, but the calls need to resemble the Qt5 api which splitted QtGui into QtGui and QtWidgets.

QtPy will also add in the future some new widgets for common use, like rich text checkboxes and others.

If you experience any problem please report it in the [QtPy issue trackerhttps://github.com/spyder-ide/qtpy/issues)]( :-) 

Thanks!

**Comment by SylvainCorlay** [comment]
qtpy is heavily used in Spyder which is Python2/Python3/PySide/PyQt compatible and has a big userbase, hence I am rather confident that you should be able to use it in your application.
